apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: kyverno
      helm:
        releaseName: kyverno
      repoURL: https://kyverno.github.io/kyverno/
      targetRevision: 3.0.2
    - directory:
        recurse: true
        include: '*.yaml'
      repoURL: https://github.com/kbristow/crossplane-vcluster-argo-test
      targetRevision: HEAD
      path: additional-k8s-resources/kyverno
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true