apiVersion: v1
kind: Secret
metadata:
    name: repo-argo-helm
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    url: https://argoproj.github.io/argo-helm
    name: argo-helm
    type: helm
    insecure: "true"